### ISSUE TITLE
GetApplicationUrl Incompatible with Mendix 7.23.4

### ISSUE THREAD

**Issue by woutervanmaasakker** [mendix/CommunityCommons#82] opened 2019-05-30 09:30 UTC
When you call the java action GetApplicationUrl the call results in an error. See below:

```
Error in execution of monitored action 'GetSessionDataAction' (execution id: 1559208148849-0, execution type: CLIENT)

java.lang.ExceptionInInitializerError: null
	at communitycommons.actions.GetApplicationUrl.executeAction(GetApplicationUrl.java:30)
	at communitycommons.actions.GetApplicationUrl.executeAction(GetApplicationUrl.java:19)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:414)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:56)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.executeSync(InternalCoreBase.java:493)
	at com.mendix.modules.microflowengine.actions.other.GatewayAction.execute(GatewayAction.scala:56)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:414)
	at com.mendix.webui.actions.microflow.GoHome$.go(ShowHomePageAction.scala:42)
	at com.mendix.webui.actions.client.GetSessionDataAction.handleHomePageIfAccessible(GetSessionDataAction.scala:150)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$10(GetSessionDataAction.scala:79)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:33)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:21)
	at com.mendix.webui.actions.client.GetSessionDataAction.withState(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$9(GetSessionDataAction.scala:79)
	at scala.util.Try$.apply(Try.scala:213)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$8(GetSessionDataAction.scala:78)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$8$adapted(GetSessionDataAction.scala:76)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$4(ContextHandling.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.basis.actionmanagement.IMonitoredAction$$anon$1.execute(IMonitoredAction.scala:47)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor(IMonitoredAction.scala:49)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor$(IMonitoredAction.scala:25)
	at com.mendix.webui.requesthandling.helpers.ContextHandling$ClientMonitoredAction.monitor(ContextHandling.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:41)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:27)
	at com.mendix.webui.actions.client.GetSessionDataAction.inContext(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$6(GetSessionDataAction.scala:76)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.GetSessionDataAction.profileRequest(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.execute(GetSessionDataAction.scala:64)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:124)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:101)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:40)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:72)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:69)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:75)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.java:909)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeHandler.service(RuntimeHandler.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.mendix.logging.impl.LogManager.getLogNode(LogManager.java:72)
	at com.mendix.basis.impl.MxRuntimeImpl.getLogger(MxRuntimeImpl.java:829)
	at com.mendix.basis.component.InternalCoreBase.getLogger(InternalCoreBase.java:770)
	at com.mendix.core.Core.getLogger(Core.java:1614)
	at communitycommons.Misc.<clinit>(Misc.java:48)
	at communitycommons.actions.GetApplicationUrl.executeAction(GetApplicationUrl.java:30)
	at communitycommons.actions.GetApplicationUrl.executeAction(GetApplicationUrl.java:19)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:414)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:56)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.executeSync(InternalCoreBase.java:493)
	at com.mendix.modules.microflowengine.actions.other.GatewayAction.execute(GatewayAction.scala:56)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:201)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:157)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:79)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:57)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:55)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:150)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:155)
	at com.mendix.basis.component.InternalCoreBase.execute(InternalCoreBase.java:414)
	at com.mendix.webui.actions.microflow.GoHome$.go(ShowHomePageAction.scala:42)
	at com.mendix.webui.actions.client.GetSessionDataAction.handleHomePageIfAccessible(GetSessionDataAction.scala:150)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$10(GetSessionDataAction.scala:79)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:33)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:21)
	at com.mendix.webui.actions.client.GetSessionDataAction.withState(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$9(GetSessionDataAction.scala:79)
	at scala.util.Try$.apply(Try.scala:213)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$8(GetSessionDataAction.scala:78)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$8$adapted(GetSessionDataAction.scala:76)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$4(ContextHandling.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.basis.actionmanagement.IMonitoredAction$$anon$1.execute(IMonitoredAction.scala:47)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor(IMonitoredAction.scala:49)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor$(IMonitoredAction.scala:25)
	at com.mendix.webui.requesthandling.helpers.ContextHandling$ClientMonitoredAction.monitor(ContextHandling.scala:49)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:41)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:27)
	at com.mendix.webui.actions.client.GetSessionDataAction.inContext(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.$anonfun$execute$6(GetSessionDataAction.scala:76)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.GetSessionDataAction.profileRequest(GetSessionDataAction.scala:29)
	at com.mendix.webui.actions.client.GetSessionDataAction.execute(GetSessionDataAction.scala:64)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:124)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:101)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:40)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:72)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:69)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:75)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.java:909)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeHandler.service(RuntimeHandler.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by reinouts** [comment] 2019-06-05 07:20
Hi @woutervanmaasakker, thanks for reporting this. At this moment I can't reproduce the issue.
Which version of CommunityCommons are you using? 8.0?

**Comment by woutervanmaasakker** [comment] 2019-06-05 07:27
Hi there,

Jep, every time I am running this action I get the same error.

Currently I am using CommonityCommons version 8.0.0 with Mendix 8.0.0 BETA 1 and the same problem occurs.

**Comment by reinouts** [comment] 2019-06-05 08:24
The issue title says the problem is with 7.23.4. Are you seeing it with both 7.23.4 and 8.0.0b1, or just one of the two?

I suggest you create a minimal test project demonstrating the problem and file a support ticket with reference to this issue, because I still can't reproduce the problem locally. If there is a bug, it is probably a bug in the runtime, not in Community Commons.

**Comment by reinouts** [comment] 2019-06-19 09:12
[GetRuntimeVersion.zip](https://github.com/mendix/CommunityCommons/files/3305308/GetRuntimeVersion.zip)
Could you download this zip file, rename it to .mpk, open it in Studio Pro 8 beta 2 and tell me if the GetApplicationURL button works for you? For me it does...

**Comment by Mcpoowl** [comment] 2019-06-24 08:35
@reinouts Running in to the same problem here, with my upgraded project from 7.18.1 --> 7.23.4. After upgrading the CommunityCommons module to version 8.0, I keep running in to the above error. Any progress?

**Comment by reinouts** [comment] 2019-06-24 10:09
Hi @Mcpoowl . I still can't reproduce the issue, and my colleagues from the runtime team are at a loss what could cause this problem, based on the stack trace. So if you could provide a reproduction, that would help a lot.

**Comment by Mcpoowl** [comment] 2019-06-24 11:08
Hi @reinouts . I tried creating a new project, and imported the CC module, and the PushNotifications module (since the scheduled event that is triggered in that module gave the error) but as you'd expect.. No error. I even copied the entire UserLib directory from my 'broken' project to the new app, and it still works... But my old project still doesn't.

I could send you my complete project, but that has no data and a LOT of overkill in regards to appstore modules, so I'm not sure that would even help you, since it's just broken, and has no reproduction 'path' other than: wait 1 minute for the SE to run and witness the error in your log..

**Comment by Mcpoowl** [comment] 2019-06-24 11:23
Hi @reinouts small follow up. I changed the code on line 48 of the Misc.java file to 

`    private static final ILogNode LOG = Core.getLogger("Community Commons"); `
thus no longer needing to use the LogNodes proxy, so I commented that import, and haven't seen the error popup since.

I have no idea how this change could fix the problem though...

**Comment by reinouts** [comment] 2019-06-24 15:17
So far, we know that
a) people experiencing this issue have upgraded their Mendix project to 7.23.4 or higher
b) it has something to do with the LogNodes enumeration.

@Mcpoowl It might still be worthwhile filing a support ticket with your project, as it would allow my runtime colleagues to debug the issue.

**Comment by reinouts** [comment] 2019-06-27 13:01
@Mcpoowl I've released version 8.0.1 that refers to the LogNodes enum value's name instead of caption in Java code. Could you try if this solves your issue?

**Comment by Mcpoowl** [comment] 2019-08-01 06:22
@reinouts  Just updated the CC module in one of our projects, and still ran in to the error

ActionManager: Error occurred while running scheduled event 'ScE_SendLogsToLogstash'
3:07:21 PMAPPERRORActionManager: java.lang.NoClassDefFoundError: Could not initialize class communitycommons.Misc

Putting "Community Commons" hardcoded in the lognode works, as you might expect.

**NB** This project is in 7.22.2, but uses the latest version of CC (8.0.1)

**Comment by reinouts** [comment] 2019-08-14 15:45
Hi @Mcpoowl - please double check your CC version. As CC 8.0+ requires Mendix 7.23.4 it is quite improbable that you would be using it with 7.22.2.

**Comment by Narev** [comment] 2019-08-27 08:49
Im running cc version 8.0.1 on mx 7.23.4 without any of the above mentioned issues.

**Comment by reinouts** [comment] 2019-08-29 15:03
Closing, as non reproducable.

**Closed by reinouts** 2019-08-29 15:03 UTC
