### ISSUE TITLE
Misc java gives java compile error when upgrading module from Mx 6 to Mx7

### ISSUE THREAD

**Issue by ivosturm** [mendix/CommunityCommons#39] opened 2017-08-01 08:35 UTC
This error is thrown:

    [javac] Compiling 157 source files to C:\Users\Ivo Strum\Documents\Mendix\OQL_Modeler_Mx6_2_1_Upgrade-main\deployment\run\bin
    [javac] C:\Users\Ivo Strum\Documents\Mendix\OQL_Modeler_Mx6_2_1_Upgrade-main\javasource\communitycommons\Misc.java:660: error: unreported exception COSVisitorException; must be caught or declared to be thrown
    [javac] 		overlay.overlay(new HashMap<Integer, String>()).save(baos);
    [javac] 		                                                    ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error

Changing the Misc.java file slightly to catch the COSVisitorException error solves the problem:

		try{
			overlay.overlay(new HashMap<Integer, String>()).save(baos);
		} catch (COSVisitorException e){
			logger.error("Overlay PDF, error while creating overlay: COSVisitorException");
		}

**Comment by RoelandSalij** [comment] 2017-08-14 09:26
Duplicate of #27

**Closed by RoelandSalij** 2017-08-14 09:26 UTC
Labels: duplicate
